print("This is a mean calculator LOL")
print("▓       ▓       ▓ ▓▓▓▓▓▓▓  ▓      ▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓ ▓       ▓ ▓▓▓▓▓▓▓")
print(" ▓     ▓ ▓     ▓  ▓        ▓      ▓       ▓     ▓ ▓▓     ▓▓ ▓      ")
print("  ▓   ▓   ▓   ▓   ▓▓▓▓▓▓▓  ▓      ▓       ▓     ▓ ▓ ▓   ▓ ▓ ▓▓▓▓▓▓▓")
print("   ▓ ▓     ▓ ▓    ▓        ▓      ▓       ▓     ▓ ▓  ▓ ▓  ▓ ▓      ")
print("    ▓       ▓     ▓▓▓▓▓▓▓  ▓▓▓▓▓▓ ▓▓▓▓▓▓▓ ▓▓▓▓▓▓▓ ▓   ▓   ▓ ▓▓▓▓▓▓▓")
number1 = int(input("Enter your first number"))
number2 = int(input("Enter your second number"))
number3 = int(input("Enter your third number"))
mean =(number1+number2+number3)/3
print("The mean of your numbers is", mean)
